config/routes.rb
Rails.application.routes.draw do
  resources :saunas
  resources :gyms
  resources :courts
  resources :adult_pools
  resources :kid_pools
  devise_for :users
  root 'resort#index'
  resources :registers
  get 'inicio' => 'resort#index'
  get 'option' => 'option#index'

end

app/models/adult_pool.rb
class AdultPool < ActiveRecord::Base
end

app/models/court.rb
class Court < ActiveRecord::Base
end

app/models/customer.rb
class Customer < ActiveRecord::Base
end

app/models/gym.rb
class Gym < ActiveRecord::Base
end

app/models/kid_pool.rb
class KidPool < ActiveRecord::Base
end

app/models/sauna.rb
class Sauna < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/adult_pools_controller.rb
class AdultPoolsController < ApplicationController
  before_action :set_adult_pool, only: [:show, :edit, :update, :destroy]

  # GET /adult_pools
  # GET /adult_pools.json
  def index
    @adult_pools = AdultPool.all
  end

  # GET /adult_pools/1
  # GET /adult_pools/1.json
  def show
  end

  # GET /adult_pools/new
  def new
    @adult_pool = AdultPool.new
  end

  # GET /adult_pools/1/edit
  def edit
  end

  # POST /adult_pools
  # POST /adult_pools.json
  def create
    @adult_pool = AdultPool.new(adult_pool_params)

    respond_to do |format|
      if @adult_pool.save
        format.html { redirect_to @adult_pool, notice: 'Adult pool was successfully created.' }
        format.json { render :show, status: :created, location: @adult_pool }
      else
        format.html { render :new }
        format.json { render json: @adult_pool.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adult_pools/1
  # PATCH/PUT /adult_pools/1.json
  def update
    respond_to do |format|
      if @adult_pool.update(adult_pool_params)
        format.html { redirect_to @adult_pool, notice: 'Adult pool was successfully updated.' }
        format.json { render :show, status: :ok, location: @adult_pool }
      else
        format.html { render :edit }
        format.json { render json: @adult_pool.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adult_pools/1
  # DELETE /adult_pools/1.json
  def destroy
    @adult_pool.destroy
    respond_to do |format|
      format.html { redirect_to adult_pools_url, notice: 'Adult pool was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adult_pool
      @adult_pool = AdultPool.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def adult_pool_params
      params.require(:adult_pool).permit(:date, :idUser)
    end
end

app/controllers/choice_controller.rb
class ChoiceController < ApplicationController
end

app/controllers/courts_controller.rb
class CourtsController < ApplicationController
  before_action :set_court, only: [:show, :edit, :update, :destroy]

  # GET /courts
  # GET /courts.json
  def index
    @courts = Court.all
  end

  # GET /courts/1
  # GET /courts/1.json
  def show
  end

  # GET /courts/new
  def new
    @court = Court.new
  end

  # GET /courts/1/edit
  def edit
  end

  # POST /courts
  # POST /courts.json
  def create
    @court = Court.new(court_params)

    respond_to do |format|
      if @court.save
        format.html { redirect_to @court, notice: 'Court was successfully created.' }
        format.json { render :show, status: :created, location: @court }
      else
        format.html { render :new }
        format.json { render json: @court.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courts/1
  # PATCH/PUT /courts/1.json
  def update
    respond_to do |format|
      if @court.update(court_params)
        format.html { redirect_to @court, notice: 'Court was successfully updated.' }
        format.json { render :show, status: :ok, location: @court }
      else
        format.html { render :edit }
        format.json { render json: @court.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courts/1
  # DELETE /courts/1.json
  def destroy
    @court.destroy
    respond_to do |format|
      format.html { redirect_to courts_url, notice: 'Court was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_court
      @court = Court.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def court_params
      params.require(:court).permit(:date, :idUser)
    end
end

app/controllers/gyms_controller.rb
class GymsController < ApplicationController
  before_action :set_gym, only: [:show, :edit, :update, :destroy]

  # GET /gyms
  # GET /gyms.json
  def index
    @gyms = Gym.all
  end

  # GET /gyms/1
  # GET /gyms/1.json
  def show
  end

  # GET /gyms/new
  def new
    @gym = Gym.new
  end

  # GET /gyms/1/edit
  def edit
  end

  # POST /gyms
  # POST /gyms.json
  def create
    @gym = Gym.new(gym_params)

    respond_to do |format|
      if @gym.save
        format.html { redirect_to @gym, notice: 'Gym was successfully created.' }
        format.json { render :show, status: :created, location: @gym }
      else
        format.html { render :new }
        format.json { render json: @gym.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gyms/1
  # PATCH/PUT /gyms/1.json
  def update
    respond_to do |format|
      if @gym.update(gym_params)
        format.html { redirect_to @gym, notice: 'Gym was successfully updated.' }
        format.json { render :show, status: :ok, location: @gym }
      else
        format.html { render :edit }
        format.json { render json: @gym.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gyms/1
  # DELETE /gyms/1.json
  def destroy
    @gym.destroy
    respond_to do |format|
      format.html { redirect_to gyms_url, notice: 'Gym was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gym
      @gym = Gym.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gym_params
      params.require(:gym).permit(:date, :idUser)
    end
end

app/controllers/option_controller.rb
class OptionController < ApplicationController
	before_action :authenticate_user!

	def index
	end
end

app/controllers/resort_controller.rb
class ResortController < ApplicationController
	before_action :authenticate_user!, except: [:index]

	def index
	end
end

app/helpers/adult_pools_helper.rb
module AdultPoolsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/choice_helper.rb
module ChoiceHelper
end

app/helpers/courts_helper.rb
module CourtsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/gyms_helper.rb
module GymsHelper
end

app/helpers/kid_pools_helper.rb
module KidPoolsHelper
end

app/helpers/option_helper.rb
module OptionHelper
end

app/helpers/resort_helper.rb
module ResortHelper
end

app/helpers/saunas_helper.rb
module SaunasHelper
end

app/views/adult_pools/_form.html.erb
<%= form_for(@adult_pool) do |f| %>
  <% if @adult_pool.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@adult_pool.errors.count, "error") %> prohibited this adult_pool from being saved:</h2>

      <ul>
      <% @adult_pool.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :idUser %><br>
    <%= f.text_field :idUser %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/adult_pools/edit.html.erb
<h1>Editing Adult Pool</h1>

<%= render 'form' %>

<%= link_to 'Show', @adult_pool %> |
<%= link_to 'Back', adult_pools_path %>

app/views/adult_pools/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Adult Pools</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Iduser</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @adult_pools.each do |adult_pool| %>
      <tr>
        <td><%= adult_pool.date %></td>
        <td><%= adult_pool.idUser %></td>
        <td><%= link_to 'Show', adult_pool %></td>
        <td><%= link_to 'Edit', edit_adult_pool_path(adult_pool) %></td>
        <td><%= link_to 'Destroy', adult_pool, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Adult pool', new_adult_pool_path %>

app/views/adult_pools/new.html.erb
<h1>New Adult Pool</h1>

<%= render 'form' %>

<%= link_to 'Back', adult_pools_path %>

app/views/adult_pools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @adult_pool.date %>
</p>

<p>
  <strong>Iduser:</strong>
  <%= @adult_pool.idUser %>
</p>

<%= link_to 'Edit', edit_adult_pool_path(@adult_pool) %> |
<%= link_to 'Back', adult_pools_path %>