config/routes.rb
Rails.application.routes.draw do
  resources :saunas
  resources :gyms
  resources :courts
  resources :adult_pools
  resources :kid_pools
  devise_for :users
  root 'resort#index'
  resources :registers
  get 'inicio' => 'resort#index'
  get 'option' => 'option#index'

end

app/models/adult_pool.rb
class AdultPool < ActiveRecord::Base
end

app/models/court.rb
class Court < ActiveRecord::Base
end

app/models/customer.rb
class Customer < ActiveRecord::Base
end

app/models/gym.rb
class Gym < ActiveRecord::Base
end

app/models/kid_pool.rb
class KidPool < ActiveRecord::Base
end

app/models/sauna.rb
class Sauna < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/choice_controller.rb
class ChoiceController < ApplicationController
end

app/controllers/courts_controller.rb
class CourtsController < ApplicationController
  before_action :set_court, only: [:show, :edit, :update, :destroy]

  # GET /courts
  # GET /courts.json
  def index
    @courts = Court.all
  end

  # GET /courts/1
  # GET /courts/1.json
  def show
  end

  # GET /courts/new
  def new
    @court = Court.new
  end

  # GET /courts/1/edit
  def edit
  end

  # POST /courts
  # POST /courts.json
  def create
    @court = Court.new(court_params)

    respond_to do |format|
      if @court.save
        format.html { redirect_to @court, notice: 'Court was successfully created.' }
        format.json { render :show, status: :created, location: @court }
      else
        format.html { render :new }
        format.json { render json: @court.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courts/1
  # PATCH/PUT /courts/1.json
  def update
    respond_to do |format|
      if @court.update(court_params)
        format.html { redirect_to @court, notice: 'Court was successfully updated.' }
        format.json { render :show, status: :ok, location: @court }
      else
        format.html { render :edit }
        format.json { render json: @court.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courts/1
  # DELETE /courts/1.json
  def destroy
    @court.destroy
    respond_to do |format|
      format.html { redirect_to courts_url, notice: 'Court was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_court
      @court = Court.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def court_params
      params.require(:court).permit(:date, :idUser)
    end
end

app/controllers/gyms_controller.rb
class GymsController < ApplicationController
  before_action :set_gym, only: [:show, :edit, :update, :destroy]

  # GET /gyms
  # GET /gyms.json
  def index
    @gyms = Gym.all
  end

  # GET /gyms/1
  # GET /gyms/1.json
  def show
  end

  # GET /gyms/new
  def new
    @gym = Gym.new
  end

  # GET /gyms/1/edit
  def edit
  end

  # POST /gyms
  # POST /gyms.json
  def create
    @gym = Gym.new(gym_params)

    respond_to do |format|
      if @gym.save
        format.html { redirect_to @gym, notice: 'Gym was successfully created.' }
        format.json { render :show, status: :created, location: @gym }
      else
        format.html { render :new }
        format.json { render json: @gym.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gyms/1
  # PATCH/PUT /gyms/1.json
  def update
    respond_to do |format|
      if @gym.update(gym_params)
        format.html { redirect_to @gym, notice: 'Gym was successfully updated.' }
        format.json { render :show, status: :ok, location: @gym }
      else
        format.html { render :edit }
        format.json { render json: @gym.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gyms/1
  # DELETE /gyms/1.json
  def destroy
    @gym.destroy
    respond_to do |format|
      format.html { redirect_to gyms_url, notice: 'Gym was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gym
      @gym = Gym.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gym_params
      params.require(:gym).permit(:date, :idUser)
    end
end

app/controllers/option_controller.rb
class OptionController < ApplicationController
	before_action :authenticate_user!

	def index
	end
end

app/controllers/resort_controller.rb
class ResortController < ApplicationController
	before_action :authenticate_user!, except: [:index]

	def index
	end
end

app/controllers/saunas_controller.rb
class SaunasController < ApplicationController
  before_action :set_sauna, only: [:show, :edit, :update, :destroy]

  # GET /saunas
  # GET /saunas.json
  def index
    @saunas = Sauna.all
  end

  # GET /saunas/1
  # GET /saunas/1.json
  def show
  end

  # GET /saunas/new
  def new
    @sauna = Sauna.new
  end

  # GET /saunas/1/edit
  def edit
  end

  # POST /saunas
  # POST /saunas.json
  def create
    @sauna = Sauna.new(sauna_params)

    respond_to do |format|
      if @sauna.save
        format.html { redirect_to @sauna, notice: 'Sauna was successfully created.' }
        format.json { render :show, status: :created, location: @sauna }
      else
        format.html { render :new }
        format.json { render json: @sauna.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /saunas/1
  # PATCH/PUT /saunas/1.json
  def update
    respond_to do |format|
      if @sauna.update(sauna_params)
        format.html { redirect_to @sauna, notice: 'Sauna was successfully updated.' }
        format.json { render :show, status: :ok, location: @sauna }
      else
        format.html { render :edit }
        format.json { render json: @sauna.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /saunas/1
  # DELETE /saunas/1.json
  def destroy
    @sauna.destroy
    respond_to do |format|
      format.html { redirect_to saunas_url, notice: 'Sauna was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sauna
      @sauna = Sauna.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sauna_params
      params.require(:sauna).permit(:date, :idUser)
    end
end

app/helpers/adult_pools_helper.rb
module AdultPoolsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/choice_helper.rb
module ChoiceHelper
end

app/helpers/courts_helper.rb
module CourtsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/gyms_helper.rb
module GymsHelper
end

app/helpers/kid_pools_helper.rb
module KidPoolsHelper
end

app/helpers/option_helper.rb
module OptionHelper
end

app/helpers/resort_helper.rb
module ResortHelper
end

app/helpers/saunas_helper.rb
module SaunasHelper
end

app/views/courts/_form.html.erb
<%= form_for(@court) do |f| %>
  <% if @court.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@court.errors.count, "error") %> prohibited this court from being saved:</h2>

      <ul>
      <% @court.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :idUser %><br>
    <%= f.text_field :idUser %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courts/edit.html.erb
<h1>Editing Court</h1>

<%= render 'form' %>

<%= link_to 'Show', @court %> |
<%= link_to 'Back', courts_path %>

app/views/courts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Courts</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Iduser</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courts.each do |court| %>
      <tr>
        <td><%= court.date %></td>
        <td><%= court.idUser %></td>
        <td><%= link_to 'Show', court %></td>
        <td><%= link_to 'Edit', edit_court_path(court) %></td>
        <td><%= link_to 'Destroy', court, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Court', new_court_path %>

app/views/courts/new.html.erb
<h1>New Court</h1>

<%= render 'form' %>

<%= link_to 'Back', courts_path %>

app/views/courts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @court.date %>
</p>

<p>
  <strong>Iduser:</strong>
  <%= @court.idUser %>
</p>

<%= link_to 'Edit', edit_court_path(@court) %> |
<%= link_to 'Back', courts_path %>

app/views/gyms/_form.html.erb
<%= form_for(@gym) do |f| %>
  <% if @gym.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gym.errors.count, "error") %> prohibited this gym from being saved:</h2>

      <ul>
      <% @gym.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :idUser %><br>
    <%= f.text_field :idUser %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gyms/edit.html.erb
<h1>Editing Gym</h1>

<%= render 'form' %>

<%= link_to 'Show', @gym %> |
<%= link_to 'Back', gyms_path %>

app/views/gyms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Gyms</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Iduser</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gyms.each do |gym| %>
      <tr>
        <td><%= gym.date %></td>
        <td><%= gym.idUser %></td>
        <td><%= link_to 'Show', gym %></td>
        <td><%= link_to 'Edit', edit_gym_path(gym) %></td>
        <td><%= link_to 'Destroy', gym, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gym', new_gym_path %>

app/views/gyms/new.html.erb
<h1>New Gym</h1>

<%= render 'form' %>

<%= link_to 'Back', gyms_path %>

app/views/gyms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @gym.date %>
</p>

<p>
  <strong>Iduser:</strong>
  <%= @gym.idUser %>
</p>

<%= link_to 'Edit', edit_gym_path(@gym) %> |
<%= link_to 'Back', gyms_path %>

app/views/saunas/_form.html.erb
<%= form_for(@sauna) do |f| %>
  <% if @sauna.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sauna.errors.count, "error") %> prohibited this sauna from being saved:</h2>

      <ul>
      <% @sauna.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :idUser %><br>
    <%= f.text_field :idUser %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/saunas/edit.html.erb
<h1>Editing Sauna</h1>

<%= render 'form' %>

<%= link_to 'Show', @sauna %> |
<%= link_to 'Back', saunas_path %>

app/views/saunas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Saunas</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Iduser</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @saunas.each do |sauna| %>
      <tr>
        <td><%= sauna.date %></td>
        <td><%= sauna.idUser %></td>
        <td><%= link_to 'Show', sauna %></td>
        <td><%= link_to 'Edit', edit_sauna_path(sauna) %></td>
        <td><%= link_to 'Destroy', sauna, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sauna', new_sauna_path %>

app/views/saunas/new.html.erb
<h1>New Sauna</h1>

<%= render 'form' %>

<%= link_to 'Back', saunas_path %>

app/views/saunas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @sauna.date %>
</p>

<p>
  <strong>Iduser:</strong>
  <%= @sauna.idUser %>
</p>

<%= link_to 'Edit', edit_sauna_path(@sauna) %> |
<%= link_to 'Back', saunas_path %>